"""
Architecture Diagram - Visual representation of TerminAI architecture
"""
def print_architecture_diagram():
    """Print a visual diagram of the TerminAI architecture"""
    print("=== TerminAI Complete Architecture ===")
    print()
    
    print("┌─────────────────────────────────────────────────────────────────┐")
    print("│                      HOST MACHINE                           │")
    print("├─────────────────────────────────────────────────────────────────┤")
    print("│  ┌──────────────────────────────────────────────────────────┐ │")
    print("│  │ VS Code Extension (TypeScript/Node.js)                  │ │")
    print("│  └──────────────────────────────────────────────────────────┘ │")
    print("│                                                                 │")
    print("│  ┌──────────────────────────────────────────────────────────┐ │")
    print("│  │ Host Chrome Service (Python)                            │ │")
    print("│  └──────────────────────────────────────────────────────────┘ │")
    print("│                                                                 │")
    print("│  ┌──────────────────────────────────────────────────────────┐ │")
    print("│  │ Podman (Container Runtime)                              │ │")
    print("│  └──────────────────────────────────────────────────────────┘ │")
    print("│          │                                                   │")
    print("│          ▼                                                   │")
    print("│  ┌──────────────────────────────────────────────────────────┐ │")
    print("│  │ Container: MCP Server (Python)                          │ │")
    print("│  │ - ChromeManager                                         │ │")
    print("│  │ - Browser Automation                                    │ │")
    print("│  │ - AI Handlers                                           │ │")
    print("│  └──────────────────────────────────────────────────────────┘ │")
    print("│          │                                                   │")
    print("│          ▼ 9223 (Host Service)                              │")
    print("│          ▼ 9222 (Chrome Debug)                              │")
    print("│                                                                 │")
    print("│  ┌──────────────────────────────────────────────────────────┐ │")
    print("│  │ Chrome Browser                                          │ │")
    print("│  │ - Remote Debug Port: 9222                               │ │")
    print("│  └──────────────────────────────────────────────────────────┘ │")
    print("└─────────────────────────────────────────────────────────────────┘")
    print()
    print("                          │")
    print("                          ▼")
    print("                   Internet Access")
    print("                          │")
    print("                          ▼")
    print("                   DeepSeek AI Service")
    print()
    print("=== Communication Flow ===")
    print("1. VS Code Extension ↔ MCP Server (Container)")
    print("2. MCP Server → Host Chrome Service (Port 9223)")
    print("3. Host Chrome Service → Start Chrome")
    print("4. MCP Server ↔ Chrome Browser (Port 9222)")
    print("5. Chrome Browser → DeepSeek AI (Internet)")


if __name__ == "__main__":
    print_architecture_diagram()