version: '1.0'
name: terminail-mcp-server-build
displayName: Terminail MCP Server Build
triggers:
  push:
    branches:
      precise:
        - main
stages:
  - name: buildAndPush
    displayName: Build and Push
    strategy: naturally
    trigger: auto
    executor:
      - type: script
        name: buildAndPush
        displayName: Build and Push Container
        tool: shell
        script: |
          #!/bin/bash
          set -e
          
          # Build the container image
          docker build -t terminail-mcp-server:${GITEE_GIT_COMMIT} -f container/Containerfile container/
          
          # Tag as latest
          docker tag terminail-mcp-server:${GITEE_GIT_COMMIT} terminail-mcp-server:latest
          
          # Push to Gitee Container Registry (if credentials are configured)
          # docker push terminail-mcp-server:${GITEE_GIT_COMMIT}
          # docker push terminail-mcp-server:latest
          
          echo "Container image built successfully: terminail-mcp-server:${GITEE_GIT_COMMIT}"